[paths]
cv_markdown_dir = "data/generated/cv/markdown"
cv_pdf_dir = "data/generated/cv/pdf"
cv_struct_json_dir = "data/generated/cv/struct_json"
rfp_struct_json_dir = "data/generated/rfp/struct_json"
rfp_markdown_dir = "data/generated/rfp/markdown"
rfp_pdf_dir = "data/generated/rfp/pdf"
